// Code generated by go generate ./protocol; DO NOT EDIT.

export interface Admitted {
  input_id: string;
  seq: number;
  command?: string;
}

export interface BaseRef {
  ref: string;
  sha: string;
}

export interface ChangedFile {
  path: string;
  old_path?: string;
  status: string;
  additions: number;
  deletions: number;
  binary: boolean;
  large: boolean;
}

export interface CommandArg {
  name: string;
  type: string;
  optional?: boolean;
}

export interface CommandEntry {
  name: string;
  aliases?: string[];
  kind: string;
  op?: string;
  summary: string;
  arg_hint?: string;
  args?: CommandArg[];
  category: string;
  available_during_task?: boolean;
  destructive?: boolean;
  method?: string;
  path?: string;
}

export interface CommandSupport {
  supported: boolean;
  reason?: string;
}

export interface Commands {
  commands: CommandEntry[];
  serve_support: Record<string, CommandSupport> | null;
  discovery_errors?: string[];
}

export interface Compact {
  keep_turns?: number;
}

export interface Compacted {
  from_seq?: number;
  to_seq?: number;
  by_backend?: boolean;
  folded: boolean;
}

export interface Context {
  tokens: number;
  window: number;
}

export interface CreateSession {
  id?: string;
  model?: string;
  effort?: string;
  service_tier?: string;
  origin?: string;
  allowed_tools?: string[];
}

export interface Error {
  code: string;
  message: string;
  details: Record<string, unknown> | null;
}

export interface ErrorBody {
  error: Error;
}

export interface Event {
  seq: number;
  t: string;
  k: string;
  d: unknown;
  ephemeral?: boolean;
}

export interface EventPage {
  events: Event[];
  next?: number;
}

export interface Goal {
  condition: string;
  max_turns?: number;
}

export interface GoalView {
  condition: string;
  max_turns?: number;
  state: string;
  turns: number;
  reason?: string;
  retry_at?: string;
}

export interface Info {
  name: string;
  origin: string;
  command: string[];
  dir?: string;
  env_names?: string[];
  ports?: number[];
  ready_regex?: string;
  ready_port?: number;
  ready_http?: string;
  ready_timeout: string;
  status: Status;
}

export interface Input {
  id: string;
  parts: Part[];
  delivery?: string;
  source?: string;
  expected_turn_id?: string;
}

export interface Interrupt {
  turn_id?: string;
  tree?: boolean;
}

export interface ItemFrame {
  item_id: string;
  turn_id: string;
  type?: string;
  text?: string;
}

export interface LastTurn {
  turn_id: string;
  stop_reason: string;
  cause?: string;
  error?: string;
}

export interface Model {
  id: string;
  provider: string;
  context_window: number;
}

export interface Part {
  type: string;
  text?: string;
  media_type?: string;
  data?: string;
}

export interface Plugin {
  name: string;
  state: string;
  tools: string[];
  hooks: string[];
}

export interface Resolution {
  answer?: unknown;
  dismiss?: boolean;
}

export interface Session {
  id: string;
  parent_id?: string;
  origin: string;
  model: string;
  effort?: string;
  service_tier?: string;
  status: string;
  turn_id?: string;
  queued?: string[];
  goal?: GoalView;
  usage: Usage;
  context: Context;
  last_turn?: LastTurn;
  compaction_count?: number;
  subscription_usage: SubscriptionUsage | null;
  plugins?: Plugin[];
  head_seq: number;
  synced_seq: number;
  created_at: string;
  updated_at: string;
}

export interface SessionPage {
  sessions: Session[];
  next?: string;
}

export interface SettingsPatch {
  model?: string;
  effort?: string;
  service_tier?: string;
}

export interface Status {
  name: string;
  state?: string;
  pid?: number;
  started_at?: string;
  finished_at?: string;
  exit_code?: number;
  ready: boolean;
  log: string;
  note?: string;
  ports?: number[];
}

export interface StatusFrame {
  status: string;
  turn_id: string;
  attempt?: number;
  next_at?: string;
}

export interface SubscriptionOverage {
  in_use: boolean;
  status: string;
  resets_at: number;
}

export interface SubscriptionUsage {
  provider: string;
  plan: string;
  windows: SubscriptionUsageWindow[];
  overage?: SubscriptionOverage;
  captured_at: number;
}

export interface SubscriptionUsageWindow {
  key: string;
  label: string;
  used_percent: number;
  resets_at: number;
}

export interface SyncAck {
  head: number;
}

export interface SyncBatch {
  epoch: number;
  session: string;
  from_seq: number;
  records: string[];
  blobs?: Record<string, string>;
}

export interface Usage {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens?: number;
  cache_write_tokens?: number;
}

export interface WorkspaceChanges {
  dir: string;
  scope: string;
  branch: string;
  head: string;
  base?: BaseRef;
  files: ChangedFile[];
  patch: string;
  truncated: boolean;
}

export interface Operations {
  createSession: { query: Record<string, never>; request: CreateSession; response: Session };
  listSessions: { query: { after?: string; limit?: number }; request: void; response: SessionPage };
  getSession: { query: Record<string, never>; request: void; response: Session };
  endSession: { query: Record<string, never>; request: void; response: void };
  updateSession: { query: Record<string, never>; request: SettingsPatch; response: Session };
  submitInput: { query: Record<string, never>; request: Input; response: Admitted };
  listInputs: { query: Record<string, never>; request: void; response: string[] };
  withdrawInput: { query: Record<string, never>; request: void; response: void };
  interruptSession: { query: Record<string, never>; request: Interrupt; response: void };
  compactSession: { query: Record<string, never>; request: Compact; response: Compacted };
  resolveRequest: { query: Record<string, never>; request: Resolution; response: void };
  setGoal: { query: Record<string, never>; request: Goal; response: Session };
  clearGoal: { query: Record<string, never>; request: void; response: void };
  listEvents: { query: { after?: string; limit?: number }; request: void; response: EventPage };
  listModels: { query: Record<string, never>; request: void; response: Model[] };
  listCommands: { query: Record<string, never>; request: void; response: Commands };
  listProcesses: { query: Record<string, never>; request: void; response: Info[] };
  startProcess: { query: Record<string, never>; request: void; response: Status };
  stopProcess: { query: Record<string, never>; request: void; response: Status };
  restartProcess: { query: Record<string, never>; request: void; response: Status };
  processLogs: { query: { tail?: number }; request: void; response: { content: string; status: Status; } };
  workspaceChanges: { query: { scope?: string; dir?: string }; request: void; response: WorkspaceChanges };
  health: { query: Record<string, never>; request: void; response: Record<string, string> };
}

export const routes = [
  { name: "createSession", method: "POST", path: "/sessions", status: 201, stream: false },
  { name: "listSessions", method: "GET", path: "/sessions", status: 200, stream: false },
  { name: "getSession", method: "GET", path: "/sessions/{id}", status: 200, stream: false },
  { name: "endSession", method: "DELETE", path: "/sessions/{id}", status: 204, stream: false },
  { name: "updateSession", method: "PATCH", path: "/sessions/{id}", status: 200, stream: false },
  { name: "submitInput", method: "POST", path: "/sessions/{id}/inputs", status: 201, stream: false },
  { name: "listInputs", method: "GET", path: "/sessions/{id}/inputs", status: 200, stream: false },
  { name: "withdrawInput", method: "DELETE", path: "/sessions/{id}/inputs/{input}", status: 204, stream: false },
  { name: "interruptSession", method: "POST", path: "/sessions/{id}/interrupt", status: 204, stream: false },
  { name: "compactSession", method: "POST", path: "/sessions/{id}/compact", status: 200, stream: false },
  { name: "resolveRequest", method: "POST", path: "/sessions/{id}/requests/{request}", status: 204, stream: false },
  { name: "setGoal", method: "PUT", path: "/sessions/{id}/goal", status: 200, stream: false },
  { name: "clearGoal", method: "DELETE", path: "/sessions/{id}/goal", status: 204, stream: false },
  { name: "listEvents", method: "GET", path: "/sessions/{id}/events", status: 200, stream: false },
  { name: "streamEvents", method: "GET", path: "/sessions/{id}/events", status: 200, stream: true },
  { name: "listModels", method: "GET", path: "/models", status: 200, stream: false },
  { name: "listCommands", method: "GET", path: "/commands", status: 200, stream: false },
  { name: "listProcesses", method: "GET", path: "/processes", status: 200, stream: false },
  { name: "startProcess", method: "POST", path: "/processes/{name}/start", status: 200, stream: false },
  { name: "stopProcess", method: "POST", path: "/processes/{name}/stop", status: 200, stream: false },
  { name: "restartProcess", method: "POST", path: "/processes/{name}/restart", status: 200, stream: false },
  { name: "processLogs", method: "GET", path: "/processes/{name}/logs", status: 200, stream: false },
  { name: "workspaceChanges", method: "GET", path: "/workspace/changes", status: 200, stream: false },
  { name: "health", method: "GET", path: "/health", status: 200, stream: false },
] as const;
