package gates

import (
	"encoding/json"
	"flag"
	"os"
	"slices"
	"strings"
	"testing"
	"testing/fstest"
)

var updateBaseline = flag.Bool("update-baseline", false, "lower baseline.json to the current metrics")

func file(s string) *fstest.MapFile { return &fstest.MapFile{Data: []byte(s)} }

func longFunc(n int) string {
	return "package a\n\nfunc F() {\n" + strings.Repeat("\t_ = 1\n", n) + "}\n"
}

func rules(vs []Violation) []string {
	var out []string
	for _, v := range vs {
		out = append(out, v.Path+":"+v.Rule)
	}
	slices.Sort(out)
	return out
}

var checkCases = []struct {
	name string
	fs   fstest.MapFS
	base Report
	want []string
}{
	{
		name: "package_doc_in_doc_go_not_counted",
		fs:   fstest.MapFS{"a/doc.go": file("// Package a x.\n// y\n// z\n// w\npackage a\n")},
	},
	{
		name: "new_file_comment_bloat_fails",
		fs:   fstest.MapFS{"a/a.go": file("package a\n// x\n// y\n// z\nvar A = 1\n")},
		want: []string{"a/a.go:comment_share"},
	},
	{
		name: "baseline_file_may_not_grow",
		fs:   fstest.MapFS{"a/a.go": file("package a\n// x\n// y\n// z\nvar A = 1\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 5, CommentLines: 2, CodeLines: 2}}},
		want: []string{"a/a.go:ratchet"},
	},
	{
		name: "baseline_file_may_grow_code_while_share_falls",
		fs:   fstest.MapFS{"a/a.go": file("package a\n// x\n// y\n// z\nvar A = 1\nvar B = 2\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 5, CommentLines: 3, CodeLines: 2}}},
	},
	{
		name: "baseline_file_may_shrink",
		fs:   fstest.MapFS{"a/a.go": file("package a\n// x\nvar A = 1\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 5, CommentLines: 3, CodeLines: 2}}},
	},
	{
		name: "history_marker_new_file_fails",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\n// fixed in #123\nvar A = 1\nvar B = 2\nvar C = 3\n")},
		want: []string{"a/a.go:history"},
	},
	{
		name: "history_marker_at_baseline_passes",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\n// fixed in #123\nvar A = 1\nvar B = 2\nvar C = 3\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 6, CommentLines: 1, CodeLines: 4, HistoryMarkers: 1}}},
	},
	{
		name: "history_marker_above_baseline_fails",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\n// fixed in #123 and #124\nvar A = 1\nvar B = 2\nvar C = 3\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 6, CommentLines: 1, CodeLines: 4, HistoryMarkers: 1}}},
		want: []string{"a/a.go:ratchet"},
	},
	{
		name: "history_marker_below_baseline_passes",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\nvar A = 1\nvar B = 2\nvar C = 3\n")},
		base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 6, CommentLines: 1, CodeLines: 4, HistoryMarkers: 1}}},
	},
	{
		name: "comment_share_at_limit_passes",
		fs:   fstest.MapFS{"a/a.go": file("package a\n" + strings.Repeat("// x\n", 25) + strings.Repeat("var _ = 1\n", 74))},
	},
	{
		name: "comment_share_above_limit_fails",
		fs:   fstest.MapFS{"a/a.go": file("package a\n" + strings.Repeat("// x\n", 26) + strings.Repeat("var _ = 1\n", 73))},
		want: []string{"a/a.go:comment_share"},
	},
	{
		name: "func_with_line_directive_measured_by_raw_lines",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\nfunc F() {\n//line x.go:1\n" + strings.Repeat("\t_ = 1\n", 80) + "}\n")},
		want: []string{"a/a.go:long_func"},
	},
	{
		name: "long_func_new_file_fails",
		fs:   fstest.MapFS{"a/a.go": file(longFunc(80))},
		want: []string{"a/a.go:long_func"},
	},
	{
		name: "func_at_limit_passes",
		fs:   fstest.MapFS{"a/a.go": file(longFunc(79))},
	},
	{
		name: "file_size_new_file_fails",
		fs:   fstest.MapFS{"a/a.go": file("package a\n" + strings.Repeat("var _ = 1\n", 800))},
		want: []string{"a/a.go:file_size"},
	},
	{
		name: "file_at_size_limit_passes",
		fs:   fstest.MapFS{"a/a.go": file("package a\n" + strings.Repeat("var _ = 1\n", 799))},
	},
	{
		name: "sleep_in_non_test_file_passes",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\nimport \"time\"\n\nfunc F() { time.Sleep(1) }\n")},
	},
	{
		name: "line_directive_does_not_remap_positions",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\n//line other.go:500\nvar A = 1 // tail\nvar B = 2\n")},
	},
	{
		name: "generated_file_skipped",
		fs: fstest.MapFS{"a/a.go": file("// Code generated by x. DO NOT EDIT.\n\npackage a\n// used to be #12\n// x\n// y\n" +
			strings.Repeat("var _ = 1\n", 900))},
	},
	{
		name: "directives_not_comments",
		fs:   fstest.MapFS{"a/a.go": file("package a\n\n//go:generate x\n//nolint:all\n//lint:ignore X y\nvar A = 1\n")},
	},
	{
		name: "sleep_in_new_test_fails",
		fs:   fstest.MapFS{"a/a_test.go": file("package a\n\nimport (\n\t\"testing\"\n\t\"time\"\n)\n\nfunc TestX(t *testing.T) {\n\ttime.Sleep(1)\n\t<-time.After(1)\n}\n")},
		want: []string{"a/a_test.go:sleep_after"},
	},
	{
		name: "testdata_ignored",
		fs:   fstest.MapFS{"a/testdata/x.go": file("package a\n// #123\n")},
	},
	{
		name: "agents_cap_root_80_scoped_25",
		fs: fstest.MapFS{
			"AGENTS.md":   file(strings.Repeat("x\n", 81)),
			"a/AGENTS.md": file(strings.Repeat("x\n", 25) + "x"),
			"b/AGENTS.md": file(strings.Repeat("x\n", 25)),
		},
		want: []string{"AGENTS.md:agents_cap", "a/AGENTS.md:agents_cap"},
	},
	{
		name: "package_ratio_may_not_rise",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\n"),
			"a/a_test.go": file("package a\nvar B = 1\nvar C = 1\nvar D = 1\n"),
		},
		base: Report{Packages: map[string]PackageMetrics{"a": {TestLines: 2, CodeLines: 2}}},
		want: []string{"a:test_ratio"},
	},
	{
		name: "deleting_code_with_unchanged_tests_passes",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\n"),
			"a/a_test.go": file("package a\nvar B = 1\nvar C = 1\nvar D = 1\n"),
		},
		base: Report{Packages: map[string]PackageMetrics{"a": {TestLines: 4, CodeLines: 4}}},
	},
	{
		name: "first_test_in_untested_package_passes",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\nvar B = 1\nvar C = 1\nvar D = 1\n"),
			"a/a_test.go": file("package a\nvar T = 1\n"),
		},
		base: Report{Packages: map[string]PackageMetrics{"a": {TestLines: 0, CodeLines: 5}}},
	},
	{
		name: "new_package_over_test_ratio_limit_fails",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\n"),
			"a/a_test.go": file("package a\nvar B = 1\nvar C = 1\nvar D = 1\n"),
		},
		want: []string{"a:test_ratio"},
	},
	{
		name: "new_package_at_test_ratio_limit_passes",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\n"),
			"a/a_test.go": file("package a\nvar T = 1\nvar U = 1\n"),
		},
	},
	{
		name: "baseline_package_may_not_rise_below_new_package_limit",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\nvar B = 1\nvar C = 1\n"),
			"a/a_test.go": file("package a\nvar T = 1\nvar U = 1\nvar V = 1\n"),
		},
		base: Report{Packages: map[string]PackageMetrics{"a": {TestLines: 2, CodeLines: 4}}},
		want: []string{"a:test_ratio"},
	},
	{
		name: "new_package_within_test_ratio_limit_passes",
		fs: fstest.MapFS{
			"a/a.go":      file("package a\nvar A = 1\nvar B = 1\nvar C = 1\n"),
			"a/a_test.go": file("package a\nvar T = 1\nvar U = 1\nvar V = 1\n"),
		},
	},
}

func TestCheck(t *testing.T) {
	for _, tc := range checkCases {
		t.Run(tc.name, func(t *testing.T) {
			r, err := Collect(tc.fs)
			if err != nil {
				t.Fatal(err)
			}
			want := slices.Clone(tc.want)
			slices.Sort(want)
			got := rules(Check(r, tc.base))
			if !slices.Equal(got, want) {
				t.Fatalf("violations = %v, want %v", got, want)
			}
		})
	}
}

func TestHistoryPattern(t *testing.T) {
	for text, want := range map[string]bool{
		"fixed in #123":         true,
		"on 2026-10-02":         true,
		"previously did x":      true,
		"no longer needed":      true,
		"used to be x":          true,
		"review finding 3":      true,
		"fix rounds":            true,
		"fix round":             true,
		"review rounds":         true,
		"review caught it":      true,
		"copilot said":          true,
		"Round 1: model calls":  false,
		"argv used to spawn":    false,
		"stop after finding it": false,
		"use x instead of y":    false,
		"around 12 items":       false,
		"the round trip":        false,
		"a rounds table":        false,
		"issue 5 is not marked": false,
	} {
		if got := historyRE.MatchString(text); got != want {
			t.Errorf("historyRE.MatchString(%q) = %v, want %v", text, got, want)
		}
	}
}

func TestCommentShareDetailNamesCounts(t *testing.T) {
	vs := absolutes(FileMetrics{CommentLines: 26, CodeLines: 74})
	if len(vs) != 1 || vs[0].Detail != "26 of 100 lines are comments, limit 25%" {
		t.Fatalf("violations = %+v", vs)
	}
}

func TestCollectCounts(t *testing.T) {
	r, err := Collect(fstest.MapFS{"a/a.go": file("package a\n\n// x\n/* y\nz */\nvar A = 1 // tail\n")})
	if err != nil {
		t.Fatal(err)
	}
	got := r.Files["a/a.go"]
	want := FileMetrics{Lines: 6, CommentLines: 3, CodeLines: 2}
	if got != want {
		t.Fatalf("metrics = %+v, want %+v", got, want)
	}
}

func TestLineDirectiveIsNotAComment(t *testing.T) {
	r, err := Collect(fstest.MapFS{"a/a.go": file("package a\n\n//line other.go:500\n//lines of prose\nvar A = 1\n")})
	if err != nil {
		t.Fatal(err)
	}
	got := r.Files["a/a.go"]
	want := FileMetrics{Lines: 5, CommentLines: 1, CodeLines: 3}
	if got != want {
		t.Fatalf("metrics = %+v, want %+v", got, want)
	}
}

func TestRatchetRefusesRise(t *testing.T) {
	file := FileMetrics{Lines: 900, CommentLines: 300, CodeLines: 600, LongFuncs: 1, HistoryMarkers: 1, SleepAfter: 1}
	pkg := PackageMetrics{TestLines: 10, CodeLines: 4}
	rises := map[string]func(*FileMetrics){
		"lines":           func(m *FileMetrics) { m.Lines++ },
		"comment_lines":   func(m *FileMetrics) { m.CommentLines++ },
		"long_funcs":      func(m *FileMetrics) { m.LongFuncs++ },
		"history_markers": func(m *FileMetrics) { m.HistoryMarkers++ },
		"sleep_after":     func(m *FileMetrics) { m.SleepAfter++ },
	}
	base := Report{Files: map[string]FileMetrics{"a.go": file}, Packages: map[string]PackageMetrics{"a": pkg}}
	for name, rise := range rises {
		t.Run(name, func(t *testing.T) {
			m := file
			rise(&m)
			r := Report{Files: map[string]FileMetrics{"a.go": m}, Packages: base.Packages}
			if _, err := Lower(r, base); err == nil {
				t.Fatal("Lower accepted a rise")
			}
			if !slices.Contains(rules(Check(r, base)), "a.go:ratchet") {
				t.Fatal("Check did not report the rise")
			}
		})
	}
	t.Run("test_ratio", func(t *testing.T) {
		r := Report{Files: base.Files, Packages: map[string]PackageMetrics{"a": {TestLines: 11, CodeLines: 4}}}
		if _, err := Lower(r, base); err == nil {
			t.Fatal("Lower accepted a rise")
		}
	})
}

func TestLowerShrinksAndRemoves(t *testing.T) {
	base := Report{Files: map[string]FileMetrics{
		"a.go": {Lines: 900, CodeLines: 880, CommentLines: 2},
		"b.go": {Lines: 900, CodeLines: 880, CommentLines: 2},
	}}
	cur := Report{Files: map[string]FileMetrics{
		"a.go": {Lines: 850, CodeLines: 830, CommentLines: 2},
		"b.go": {Lines: 100, CodeLines: 90, CommentLines: 2},
	}}
	got, err := Lower(cur, base)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := got.Files["b.go"]; ok {
		t.Fatal("b.go now meets the absolutes and must leave the baseline")
	}
	if got.Files["a.go"].Lines != 850 {
		t.Fatalf("a.go = %+v, want lowered", got.Files["a.go"])
	}
}

func TestLowerAddsNewPackage(t *testing.T) {
	cur := Report{Packages: map[string]PackageMetrics{"new": {TestLines: 3, CodeLines: 10}}}
	got, err := Lower(cur, Report{})
	if err != nil {
		t.Fatal(err)
	}
	if got.Packages["new"] != cur.Packages["new"] {
		t.Fatalf("packages = %+v, want the new package recorded", got.Packages)
	}
}

func TestRepository(t *testing.T) {
	const path = "baseline.json"
	r, err := Collect(os.DirFS("../.."))
	if err != nil {
		t.Fatal(err)
	}
	var base Report
	data, err := os.ReadFile(path)
	missing := os.IsNotExist(err)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &base); err != nil {
			t.Fatal(err)
		}
	case !missing:
		t.Fatal(err)
	}
	if *updateBaseline {
		next := Seed(r)
		if !missing {
			if next, err = Lower(r, base); err != nil {
				t.Fatal(err)
			}
		}
		out, err := json.MarshalIndent(next, "", "\t")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	for p, m := range r.Files {
		if share := commentShare(m); share > warnShare && share <= maxShare {
			t.Logf("warning: %s comment share %.0f%%", p, share*100)
		}
	}
	for _, v := range Check(r, base) {
		t.Errorf("%s: %s: %s", v.Path, v.Rule, v.Detail)
	}
}
