package gates

import (
	"encoding/json"
	"flag"
	"os"
	"slices"
	"strings"
	"testing"
	"testing/fstest"
)

var updateBaseline = flag.Bool("update-baseline", false, "lower baseline.json to the current metrics")

func file(s string) *fstest.MapFile { return &fstest.MapFile{Data: []byte(s)} }

func longFunc(n int) string {
	return "package a\n\nfunc F() {\n" + strings.Repeat("\t_ = 1\n", n) + "}\n"
}

func rules(vs []Violation) []string {
	var out []string
	for _, v := range vs {
		out = append(out, v.Path+":"+v.Rule)
	}
	slices.Sort(out)
	return out
}

func TestCheck(t *testing.T) {
	tests := []struct {
		name string
		fs   fstest.MapFS
		base Report
		want []string
	}{
		{
			name: "new_file_comment_bloat_fails",
			fs:   fstest.MapFS{"a/a.go": file("package a\n// x\n// y\n// z\nvar A = 1\n")},
			want: []string{"a/a.go:comment_share"},
		},
		{
			name: "baseline_file_may_not_grow",
			fs:   fstest.MapFS{"a/a.go": file("package a\n// x\n// y\n// z\nvar A = 1\n")},
			base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 5, CommentLines: 2, CodeLines: 2}}},
			want: []string{"a/a.go:ratchet"},
		},
		{
			name: "baseline_file_may_shrink",
			fs:   fstest.MapFS{"a/a.go": file("package a\n// x\nvar A = 1\n")},
			base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 5, CommentLines: 3, CodeLines: 2}}},
		},
		{
			name: "history_marker_fails_even_in_baseline",
			fs:   fstest.MapFS{"a/a.go": file("package a\n\n// fixed in #123\nvar A = 1\nvar B = 2\nvar C = 3\nvar D = 4\nvar E = 5\nvar F = 6\n")},
			base: Report{Files: map[string]FileMetrics{"a/a.go": {Lines: 9, CommentLines: 1, CodeLines: 7, HistoryMarkers: 1}}},
			want: []string{"a/a.go:history"},
		},
		{
			name: "long_func_new_file_fails",
			fs:   fstest.MapFS{"a/a.go": file(longFunc(81))},
			want: []string{"a/a.go:long_func"},
		},
		{
			name: "file_size_new_file_fails",
			fs:   fstest.MapFS{"a/a.go": file("package a\n" + strings.Repeat("var _ = 1\n", 800))},
			want: []string{"a/a.go:file_size"},
		},
		{
			name: "generated_file_skipped",
			fs: fstest.MapFS{"a/a.go": file("// Code generated by x. DO NOT EDIT.\n\npackage a\n// used to be #12\n// x\n// y\n" +
				strings.Repeat("var _ = 1\n", 900))},
		},
		{
			name: "directives_not_comments",
			fs:   fstest.MapFS{"a/a.go": file("package a\n\n//go:generate x\n//nolint:all\n//lint:ignore X y\nvar A = 1\n")},
		},
		{
			name: "sleep_in_new_test_fails",
			fs:   fstest.MapFS{"a/a_test.go": file("package a\n\nimport (\n\t\"testing\"\n\t\"time\"\n)\n\nfunc TestX(t *testing.T) {\n\ttime.Sleep(1)\n\t<-time.After(1)\n}\n")},
			want: []string{"a/a_test.go:sleep_after"},
		},
		{
			name: "testdata_ignored",
			fs:   fstest.MapFS{"a/testdata/x.go": file("package a\n// #123\n")},
		},
		{
			name: "agents_cap_root_80_scoped_25",
			fs: fstest.MapFS{
				"AGENTS.md":   file(strings.Repeat("x\n", 81)),
				"a/AGENTS.md": file(strings.Repeat("x\n", 26)),
				"b/AGENTS.md": file(strings.Repeat("x\n", 25)),
			},
			want: []string{"AGENTS.md:agents_cap", "a/AGENTS.md:agents_cap"},
		},
		{
			name: "package_ratio_may_not_rise",
			fs: fstest.MapFS{
				"a/a.go":      file("package a\nvar A = 1\n"),
				"a/a_test.go": file("package a\nvar B = 1\nvar C = 1\nvar D = 1\n"),
			},
			base: Report{Packages: map[string]PackageMetrics{"a": {TestLines: 2, CodeLines: 2}}},
			want: []string{"a:test_ratio"},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			r, err := Collect(tc.fs)
			if err != nil {
				t.Fatal(err)
			}
			want := slices.Clone(tc.want)
			slices.Sort(want)
			got := rules(Check(r, tc.base))
			if !slices.Equal(got, want) {
				t.Fatalf("violations = %v, want %v", got, want)
			}
		})
	}
}

func TestCollectCounts(t *testing.T) {
	r, err := Collect(fstest.MapFS{"a/a.go": file("package a\n\n// x\n/* y\nz */\nvar A = 1 // tail\n")})
	if err != nil {
		t.Fatal(err)
	}
	got := r.Files["a/a.go"]
	want := FileMetrics{Lines: 6, CommentLines: 3, CodeLines: 2}
	if got != want {
		t.Fatalf("metrics = %+v, want %+v", got, want)
	}
}

func TestUpdateRefusesIncrease(t *testing.T) {
	base := Report{
		Files:    map[string]FileMetrics{"a.go": {Lines: 10, CodeLines: 8, CommentLines: 2}},
		Packages: map[string]PackageMetrics{"a": {TestLines: 2, CodeLines: 4}},
	}
	rises := []Report{
		{Files: map[string]FileMetrics{"a.go": {Lines: 11, CodeLines: 8, CommentLines: 2}}, Packages: base.Packages},
		{Files: base.Files, Packages: map[string]PackageMetrics{"a": {TestLines: 3, CodeLines: 4}}},
	}
	for i, r := range rises {
		if _, err := Lower(r, base); err == nil {
			t.Fatalf("case %d: Lower accepted a rise", i)
		}
	}
}

func TestLowerShrinksAndRemoves(t *testing.T) {
	base := Report{Files: map[string]FileMetrics{
		"a.go": {Lines: 900, CodeLines: 880, CommentLines: 2},
		"b.go": {Lines: 900, CodeLines: 880, CommentLines: 2},
	}}
	cur := Report{Files: map[string]FileMetrics{
		"a.go": {Lines: 850, CodeLines: 830, CommentLines: 2},
		"b.go": {Lines: 100, CodeLines: 90, CommentLines: 2},
	}}
	got, err := Lower(cur, base)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := got.Files["b.go"]; ok {
		t.Fatal("b.go now meets the absolutes and must leave the baseline")
	}
	if got.Files["a.go"].Lines != 850 {
		t.Fatalf("a.go = %+v, want lowered", got.Files["a.go"])
	}
}

func TestRepository(t *testing.T) {
	const path = "baseline.json"
	r, err := Collect(os.DirFS("../.."))
	if err != nil {
		t.Fatal(err)
	}
	var base Report
	data, err := os.ReadFile(path)
	missing := os.IsNotExist(err)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &base); err != nil {
			t.Fatal(err)
		}
	case !missing:
		t.Fatal(err)
	}
	if *updateBaseline {
		next := Seed(r)
		if !missing {
			if next, err = Lower(r, base); err != nil {
				t.Fatal(err)
			}
		}
		out, err := json.MarshalIndent(next, "", "\t")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	for p, m := range r.Files {
		if share := commentShare(m); share > warnShare && share <= maxShare {
			t.Logf("warning: %s comment share %.0f%%", p, share*100)
		}
	}
	for _, v := range Check(r, base) {
		t.Errorf("%s: %s: %s", v.Path, v.Rule, v.Detail)
	}
}
